version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 8000:5432

  gateway:
    image: ilyxabanchichi/rsoi-lab2-gateway:latest
    restart: always
    build:
      context: ./app/Gateway
      dockerfile: ./Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:8080

volumes:
  db-data: